
version: '3.8'

services:
  springboot-app:
    image: openjdk:11
    container_name: springboot_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: health_postgres
    environment:
      POSTGRES_DB: health_alert_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: health_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: health_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
